# Generated by Django 4.1.5 on 2024-04-26 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resume_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='about_me',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
